### ISSUE TITLE
WinML Tools Link Gone?

### ISSUE THREAD

**Issue by wjohnson** [MicrosoftDocs/windows-ai-docs#1]
This [ONNX](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-build-deploy-onnx#saveconvert-your-models-to-onnx) page points us to the WinML Tools page for converting deep learning models to ONNX but the destination page no longer exists.

I ended up using the Google Cached version of the page to view the code snippets.  Any chance we could either restore the page or help out the other team with fixing the link to the WinML tool docs?

WinML Tools Page: https://docs.microsoft.com/en-us/windows/ai/convert-model-winmltools

[Google Cached version](https://webcache.googleusercontent.com/search?q=cache:cXK7P-Q_UYEJ:https://docs.microsoft.com/en-us/windows/ai/convert-model-winmltools+&cd=1&hl=en&ct=clnk&gl=us)

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
