### ISSUE TITLE
mlgen not generating cs file

### ISSUE THREAD

**Issue by Avrohom** [MicrosoftDocs/windows-ai-docs#10]
I'm submitting a…
Bug report (I searched for similar issues and did not find one)

Current behavior
mlgen is not generating cs files for imported ONNX models.

I have followed the tutorial to the dot. And of course it is a UWP desktop app.

Expected behavior
the mlgen should generate cs files.

Minimal reproduction of the problem with instructions
Selected the Assets folder in Solution Explorer. Clicked on 'Add existing item' and imported a ONNX model. Nothing happened. No cs file generated.

Environment
Windows Build Number: 17763

App min and target version: 17763 17763

OS Version (Server, IoT Core, Desktop, etc): Win 10 Desktop

Graphics Driver version:

DxDiag:

Visual Studio

  2017 (version: ) Latest
  2017 Preview (version: )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db9595e-6600-0a29-1ec5-a105bc0f1cc7
* Version Independent ID: bdbf508e-f549-44c4-7e74-91b52cce7250
* Content: [Create a Windows Machine Learning UWP application (C#)](https://docs.microsoft.com/en-us/windows/ai/windows-ml/get-started-uwp#feedback)
* Content Source: [docs/windows-ml/get-started-uwp.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/get-started-uwp.md)
* Product: **machine-learning**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
