### ISSUE TITLE
DirectML installation is confusing

### ISSUE THREAD

**Issue by velicanerdem** [MicrosoftDocs/windows-ai-docs#105]
I think this installation would be much better:

conda install numpy pandas tensorboard matplotlib tqdm pyyaml -y
pip install opencv-python
pip install wget
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch
pip install torch-directml

Pytorch version is correct and torchvision etc. can be get from conda.

**Comment by stevewhims** [comment]
Hi, @velicanerdem. Which topic is this in reference to? If you could paste in a url?

Thanks!
-Steve
