### ISSUE TITLE
Out of date instructions

### ISSUE THREAD

**Issue by rsummers11** [MicrosoftDocs/windows-ai-docs#107]
Please update this weppage. It is way out-of-date. The Python version has to be at least 3.8 for pytorch-directml to be found by pip. The mention of PyTorch 1.13 is out-of-date (latest version is 2.0). The sample code does not work on intel gpu's.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Version Independent ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Content: [Enable PyTorch with DirectML on WSL 2](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl)
* Content Source: [docs/directml/gpu-pytorch-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-wsl.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing the issue! I'm investigating.

-Steve

**Comment by stevewhims** [comment]
Just an update: this issue is on the product team subject-matter experts' radar. They have all the info from this thread. So I'll go ahead and close this issue until such time as they have the bandwidth to address it.

-Steve
