### ISSUE TITLE
Why ML Model is defined only as a file?

### ISSUE THREAD

**Issue by maruf42** [MicrosoftDocs/windows-ai-docs#116]
Why is the page https://learn.microsoft.com/en-us/windows/ai/windows-ml/what-is-a-machine-learning-model, ML Model is defined only as a file? In reality, it is an object loaded onto the memory and can be persisted as a file only for storage/porting purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e85c8e5b-d981-c2f3-2d27-927848fe7e66
* Version Independent ID: a10153c7-e612-f438-b35e-81004f1e9b6e
* Content: [What is a machine learning model?](https://learn.microsoft.com/en-us/windows/ai/windows-ml/what-is-a-machine-learning-model)
* Content Source: [docs/windows-ml/what-is-a-machine-learning-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/what-is-a-machine-learning-model.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

This is a good observation, and the wording here has been slightly updated for accuracy.
