### ISSUE TITLE
conda create --name tfdml_plugin python=3.9 <- command is not working

### ISSUE THREAD

**Issue by prashantmaurya19** [MicrosoftDocs/windows-ai-docs#117]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 764f2adc-3018-9307-941b-1e37a0ced157
* Version Independent ID: 764f2adc-3018-9307-941b-1e37a0ced157
* Content: [DirectML Plugin for TensorFlow 2](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-plugin)
* Content Source: [docs/directml/gpu-tensorflow-plugin.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-tensorflow-plugin.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **jdykhuizen**

**Comment by prashantmaurya19** [comment]
sorry for that but i tryied forth time then it work

**Comment by stevewhims** [comment]
Thanks for the update! I'll go ahead and close.

-Steve
