### ISSUE TITLE
Comments on Windows Vision Skills Tutorial

### ISSUE THREAD

**Issue by NaveenThum** [MicrosoftDocs/windows-ai-docs#117]
"A machine learning model in ONNX format to identify a face in an image and infer its sentiment". I thought we use a Windows API to detect face region, and not an ONNX model. Sentiment detection portion, on the other hand is indeed done with the ONNX model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd9c2f05-e537-3874-3ea2-bfc7b2f23558
* Version Independent ID: 9c57a643-914e-3c6b-4e55-2d069448bb77
* Content: [Create your own vision skill (C#/C++)](https://review.docs.microsoft.com/en-us/windows/ai-internal/windows-vision-skills/tutorial?branch=vision-skills-updates#feedback)
* Content Source: [docs/windows-vision-skills/tutorial.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/windows-vision-skills/tutorial.md)
* Product: **machine-learning**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Varsha-Parthasarathy** [comment]
Correct, modified the doc to reflect the same.
