### ISSUE TITLE
torch-directml version could not be found

### ISSUE THREAD

**Issue by rncwnd79** [MicrosoftDocs/windows-ai-docs#118]
The documentation is wrong.

```bash
$ pip install torch-directml
ERROR: Could not find a version that satisfies the requirement torch-directml (from versions: none)
ERROR: No matching distribution found for torch-directml
```

```bash
$ python --version
Python 3.11.4
```

WSL 2 with Ubuntu 22.04.2 LTS

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Version Independent ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Content: [Enable PyTorch with DirectML on WSL 2](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl)
* Content Source: [docs/directml/gpu-pytorch-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-wsl.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you, I'm investigating.

**Comment by stevewhims** [comment]
Just an update: this issue is on the product team subject-matter experts' radar. They have all the info from this thread. So I'll go ahead and close this issue until such time as they have the bandwidth to address it.

-Steve
