### ISSUE TITLE
More ways to get VideoFrame

### ISSUE THREAD

**Issue by NaveenThum** [MicrosoftDocs/windows-ai-docs#118]
I'd like to see more doc pointers on how to get a videoframe - not just from file picker, but also from a camera, and potentially an MP4 file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbb1a709-547b-eac8-e78b-2beb7bd1ed74
* Version Independent ID: 95724d8a-72bb-4d63-466f-52710746451d
* Content: [Create a vision skill UWP application](https://review.docs.microsoft.com/en-us/windows/ai-internal/windows-vision-skills/tutorial1?branch=vision-skills-updates#feedback)
* Content Source: [docs/windows-vision-skills/tutorial1.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/windows-vision-skills/tutorial1.md)
* Product: **machine-learning**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by BenPYeh** [comment]
At least for camera, we can link to the FrameReader documentation and sample.
