### ISSUE TITLE
pip install tensorflow-directml-plugin not version found

### ISSUE THREAD

**Issue by AM-I-Human** [MicrosoftDocs/windows-ai-docs#119]
Hello, 
`pip install tensorflow-directml-plugin` gives me
```
ERROR: Could not find a version that satisfies the requirement tensorflow-directml-plugin (from versions: none)
ERROR: No matching distribution found for tensorflow-directml-plugin
```
On python 3.11.5 I believe this is the issue

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 764f2adc-3018-9307-941b-1e37a0ced157
* Version Independent ID: 764f2adc-3018-9307-941b-1e37a0ced157
* Content: [DirectML Plugin for TensorFlow 2](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-plugin)
* Content Source: [docs/directml/gpu-tensorflow-plugin.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-tensorflow-plugin.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **jdykhuizen**

**Comment by stevewhims** [comment]
Sorry for the delay, I'm investigating!

-Steve

**Comment by PatriceVignola** [comment]
Hi @AM-I-Human,

`tensorflow-directml-plugin` doesn't support 3.11, but you should be able to install it using python 3.10.

Unfortunately we had to pause development of `tensorflow-directml-plugin` for the time being, so supporting 3.11 is not something we can do for the foreseeable future.

**Comment by stevewhims** [comment]
Thanks, all! I've completed a PR to add this info to the topic (that change is in the pipeline and on its way out to the live site now). I'll go ahead and close the issue.

Thanks!
-Steve
