### ISSUE TITLE
Variable not defined

### ISSUE THREAD

**Issue by OfficialChandrakant** [MicrosoftDocs/windows-ai-docs#120]
The variable is not defined, here , i.e. input_size
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f29e7047-7b68-3cd9-4559-ef110abaefe6
* Version Independent ID: 38f15639-5815-d091-6cf1-a32bd0884498
* Content: [Image Classification with PyTorch and Windows ML](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-intro)
* Content Source: [docs/windows-ml/tutorials/pytorch-intro.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-intro.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I believe this problem has been resolved. Moreover, the tutorial in question is likely to see further updates soon, along with many other docs in this repo.
