### ISSUE TITLE
Emoji8 sample returns a 404. 

### ISSUE THREAD

**Issue by Gauntly** [MicrosoftDocs/windows-ai-docs#122]
[Enter feedback here]
[Emoji8 sample](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/Emoji8/UWP/cs)
 returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e526d827-05b8-8e9a-80f5-c43562c1e182
* Version Independent ID: d8ea3163-5966-754a-0773-c4b40dd12654
* Content: [Introduction to Windows Machine Learning](https://learn.microsoft.com/en-us/windows/ai/windows-ml/)
* Content Source: [docs/windows-ml/index.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/index.md)
* Product: **windows**
* GitHub Login: @rosanevallim
* Microsoft Alias: **rovalli**

**Comment by QuinnRadich** [comment]
As part of ongoing updates to this documentation area, the link in question has been removed. Thank you.
