### ISSUE TITLE
Typo Neutron>Netron

### ISSUE THREAD

**Issue by waxingsatirical** [MicrosoftDocs/windows-ai-docs#126]
I think the model visualisation tool is Netron, not Neutron. A link would be handy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7323f38-3e56-688d-5cce-711a554eeed3
* Version Independent ID: 09d5d90f-483c-9951-d5ed-313c1a3330fb
* Content: [Deploy your model in a Windows app with Windows ML API](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/image-classification-deploy-model)
* Content Source: [docs/windows-ml/tutorials/image-classification-deploy-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/image-classification-deploy-model.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by stevewhims** [comment]
Fixed, thanks!
