### ISSUE TITLE
page needs update

### ISSUE THREAD

**Issue by Laurent-VueJS** [MicrosoftDocs/windows-ai-docs#128]
Ne marche plus. Version 3.7 de python recommandée plus valide
en passant par python 3.8 à la main par la suite, d'autres problèmes de version apparaissent et cette page nécessite un update

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Version Independent ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Content: [Enable PyTorch with DirectML on WSL 2](https://learn.microsoft.com/fr-fr/windows/ai/directml/gpu-pytorch-wsl)
* Content Source: [docs/directml/gpu-pytorch-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-wsl.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Merci. J'enquête.

-Steve

**Comment by stevewhims** [comment]
The product team is aware of this issue. I'll go ahead and close it until such times as the team have the bandwidth to address it.
