### ISSUE TITLE
TestModelAccuracy incorrectly named

### ISSUE THREAD

**Issue by jennabourgeois** [MicrosoftDocs/windows-ai-docs#134]
There is an error in the code.  TestModelAccuracy should be TestAccuracy in order to run the code successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b54afee7-1e3b-98f3-c25d-c0d71b82bf97
* Version Independent ID: b75b9ae6-de0e-acc3-b9cd-4918422bf7aa
* Content: [Use PyTorch to train your image classification model](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-train-model)
* Content Source: [docs/windows-ml/tutorials/pytorch-train-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-train-model.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by GrantMeStrength** [comment]
Thank you.
