### ISSUE TITLE
Inputsize not defined

### ISSUE THREAD

**Issue by jennabourgeois** [MicrosoftDocs/windows-ai-docs#135]
There is another error in the code.  Input size is not defined when creating the dummy input tensor.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b236fa85-23be-f5ec-5c5f-332937187f04
* Version Independent ID: 781552b8-a796-a963-05d3-ed98f509dbd4
* Content: [Convert your PyTorch training model to ONNX](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-convert-model)
* Content Source: [docs/windows-ml/tutorials/pytorch-convert-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-convert-model.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I believe this problem has been resolved. Moreover, the tutorial in question is likely to see further updates soon, along with many other docs in this repo.
