### ISSUE TITLE
Potential problem

### ISSUE THREAD

**Issue by Askjensen** [MicrosoftDocs/windows-ai-docs#14]
Hi, first of all great work! I've hit a problem that I though you might like to know of. In short while trying to convert from scikit learn to onnx I get an error in the parser of sklearn_convert. Even running exactly the proposed tutorial with no changes I get: 
```
Error in parse_sklearn  for var_name, initial_type in initial_types:
ValueError: too many values to unpack (expected 2)
```
I realise this could easily be a dependency problem but figured you'd still want to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bf772d-9f06-0114-305a-058c6bea5786
* Version Independent ID: 297ca67d-9d10-eb87-f26e-4d72eefe252f
* Content: [Convert ML models to ONNX with WinMLTools](https://docs.microsoft.com/en-us/windows/ai/convert-model-winmltools)
* Content Source: [docs/convert-model-winmltools.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/convert-model-winmltools.md)
* Product: **windows**
* GitHub Login: @wschin
* Microsoft Alias: **wechi**

**Comment by prabhat00155** [comment]
Thanks for your comment. The scikit code hasn't been updated I guess. The format of input_features argument in convert_sklearn() function has changed. So, you need to make the following changes:
1) Import FloatTensorType:
from onnxmltools.convert.common.data_types import FloatTensorType
2) Modify convert_sklearn() calls:
linear_svc_onnx = convert_sklearn(linear_svc, name='LinearSVC', input_features=[('input', FloatTensorType([1, 2]))]) 
linear_svr_onnx = convert_sklearn(linear_svr, name='LinearSVR', input_features=[('input', FloatTensorType([1, 2]))])
We'll update the documentation soon. Thanks!

**Comment by eliotcowley** [comment]
Hi, the documentation has been updated with @prabhat00155's changes. Thanks everyone!

**Comment by Askjensen** [comment]
thx
