### ISSUE TITLE
Not Loading a Model

### ISSUE THREAD

**Issue by vuk119** [MicrosoftDocs/windows-ai-docs#14]
Hi, 

I want to use WindowsML. I was following this tutorial:

https://docs.microsoft.com/en-us/windows/ai/windows-ml/evaluate-model-inputs

Everything worked fine! However, when I tried a different model such as mnist.onnx or my own .onnx model, I get the following errors caused during the execution of LoadModel():

Exception thrown at 0x76B83442 in test1.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x005BF2A4.

Exception thrown at 0x76B83442 in test1.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x00BCF370.

I have not changed anything in the code except for the variable modelPath...

**Comment by vuk119** [comment]
More details:

I concluded that there is a problem in loading a network with a pooling layer. For example, if I try to load the network, generated by the following code, everything works.

```
model=keras.Sequential([
    keras.layers.Conv2D(filters=64,kernel_size=[3,3],strides=2,activation='relu',padding='valid', name='conv1', input_shape=(104, 104,1)),
    keras.layers.Conv2D(filters=64,kernel_size=[3,3],strides=2,activation='relu',padding='valid', name='conv2'),
    # keras.layers.MaxPool2D(pool_size=[2,2],strides=2,padding='valid',name='pool1'),
    keras.layers.Flatten(),
    keras.layers.Activation('relu'),
    keras.layers.Dense(units=1024,activation='relu',kernel_regularizer=keras.regularizers.l2(0)) ,
    keras.layers.Dense(units=512,activation='relu',kernel_regularizer=keras.regularizers.l2(0)) ,
    keras.layers.Dense(units=297, activation='softmax')
])

onnx_model = keras2onnx.convert_keras(model, 'Test')
onnxmltools.utils.save_model(onnx_model, 'modelConv2.onnx')
```


But If I remove # from the line containing MaxPool layer I get memory error shown above.

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
