### ISSUE TITLE
(mglen)Windows Machine Learning Code Generator Can't be used in Visual Studio 2022

### ISSUE THREAD

**Issue by fangrui10** [MicrosoftDocs/windows-ai-docs#140]
The Introduction page recommands using Visual Studio 2022.
However, the Windows Machine Learning Code Generator extension doesn't have 2022 version.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7323f38-3e56-688d-5cce-711a554eeed3
* Version Independent ID: 09d5d90f-483c-9951-d5ed-313c1a3330fb
* Content: [Deploy your model in a Windows app with Windows ML API](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/image-classification-deploy-model)
* Content Source: [docs/windows-ml/tutorials/image-classification-deploy-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/image-classification-deploy-model.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by GrantMeStrength** [comment]
Thanks for your feedback. Yes, mlgen is no longer available. In general, we recommend using other application frameworks to create Windows apps. UWP is still supported, but will not be the focus of attention.
