### ISSUE TITLE
Why is the page on Tensorflow-directml-plugin still up? Was it not decided to discontinue this in favor of ONNX-runtime?

### ISSUE THREAD

**Issue by chanangaza** [MicrosoftDocs/windows-ai-docs#144]
[**** Edit by stevewhims: The topic in question is probably [Enable GPU acceleration for TensorFlow 2 with tensorflow-directml-plugin](https://learn.microsoft.com/windows/ai/directml/gpu-tensorflow-plugin) ****]

Dears, please update this page with discontinuity notice and preferably guidance regarding alternative frameworks:

1. For training, REST/grpc, to use WSL2/docker which from my experience works seamlessly at around 75% of native Windows gpu performance. The convenient access to Windows filesystem (even remote LAN folders!) is a bug plus IMO.

2. For on device from RAM inference (e.g. inspection over continuous frames), referrals to ONNX -runtime, or Tensorflow-Lite.

Discontinuity of SW projects is part of life. Nevertheless, it's always useful to receive info regarding alternative routes.

Many thanks and gratitude to those who put time and effort on the Tensorflow-directml-plugin. It was brilliant while it lasted...

**Comment by stevewhims** [comment]
Thank you! I'm investigating what we can/want-to do here.

-Steve

**Comment by stevewhims** [comment]
Thanks, @chanangaza. So far, I've just added a simple discontinuation notice to the topic. But this is on our radar in case we want to add further info. So I'll close for now.

-Steve
