### ISSUE TITLE
Why "conda install pytorch cpuonly -c pytorch" followed by "pip install torch-directml" ... cpuonly when goal is to use GPU acceleration via DirectML?

### ISSUE THREAD

**Issue by AshleyT3** [MicrosoftDocs/windows-ai-docs#147]
Why does the referenced page specify to perform "conda install pytorch **cpuonly** -c pytorch" followed by "pip install torch-**directml**" ? Use of cpuonly with goal to use DirectML to access GPU acceleration seems odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 851931b0-0646-18fc-1c3b-5f5493524330
* Version Independent ID: 851931b0-0646-18fc-1c3b-5f5493524330
* Content: [Enable PyTorch with DirectML on Windows](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows)
* Content Source: [docs/directml/gpu-pytorch-windows.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-windows.md)
* Service: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by AshleyT3** [comment]
https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows#install-pytorch-and-the-torch-directml-plugin

<img width="827" alt="image" src="https://github.com/MicrosoftDocs/windows-ai-docs/assets/32182932/b9e400c1-270d-4968-a0c5-21448daf3b12">

**Comment by stevewhims** [comment]
Thank you! I'm investigating.

**Comment by AshleyT3** [comment]
With steps on that [page](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows), GPU acceleration is certainly used despite that same page's cpu/workload qualification. (Observed by testing w/classification sample.) For those new to torch-directml, maybe clarify "... Even though 'cpuonly' is specified, GPU acceleration will be used by directml if device 'dml' is used w/applicable hardware available. ..." Generally, the qualification of 'cpu' there seems unnecessary.

**Comment by stevewhims** [comment]
Hi, the reason the topic indicates to install the cpu path first is because directml isn't included in the main branch of pytorch, since it is still in preview state.
