### ISSUE TITLE
how this differ from ml.net

### ISSUE THREAD

**Issue by vscodewinodws** [MicrosoftDocs/windows-ai-docs#15]
can some one explain how this one differs from ml.net and what  are pros and cons between windows ml and ml.net ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e526d827-05b8-8e9a-80f5-c43562c1e182
* Version Independent ID: d8ea3163-5966-754a-0773-c4b40dd12654
* Content: [Windows Machine Learning](https://docs.microsoft.com/en-us/windows/ai/windows-ml/)
* Content Source: [docs/windows-ml/index.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/index.md)
* Product: **machine-learning**
* GitHub Login: @rosanevallim
* Microsoft Alias: **rovalli**

**Comment by Sebosek** [comment]
Hi, by my humble opinion Windows ML is a set of native API in Windows OS compared to ML.NET is a framework for multiplatform CoreRT (.net core runtime), so it's not bound with Windows and your machine learning predictions can run basically on any platform (supported by .net core).
A good kind of question could be: how much faster is Windows ML compared to ML.NET...?

**Comment by popasUC** [comment]
One main difference, if I understand correctly, is that Windows ML cannot train, it can only use TRAINED models (1st paragraph in the Overview section above: "With Windows ML, developers can use trained ML models").
Another aspect might be that Windows ML seems to be limited to the ONNX format only.

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
