### ISSUE TITLE
Does ONNX opsets support version 11 on Windows 1909?

### ISSUE THREAD

**Issue by Iamnvincible** [MicrosoftDocs/windows-ai-docs#17]
There has been a long time since last document update, and Windows 1909 is released.
I wonder know is there any updates on ONNX opsets support?
I am working on an model exported from Pytorch with ONNX opsets 11.
Currently, the tools provided can not generate C# model class.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d4053d-f40c-68ac-b58e-7a73ce572714
* Version Independent ID: e584a5bd-c6fc-378f-26a5-968338147e85
* Content: [ONNX versions and Windows builds](https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions)
* Content Source: [docs/windows-ml/onnx-versions.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/onnx-versions.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by chrisjhebert1973** [comment]
Any update on this?

**Comment by QuinnRadich** [comment]
Apologies, this and some other issues fell through the cracks when the writer ownership of these docs change. I'll pursue this and update as necessary.

**Comment by chrisjhebert1973** [comment]
Thank You. Very much appreciated.

**Comment by QuinnRadich** [comment]
I can confirm that Windows 1909 does not contain any changes in opset support. ONNX opsets 9 will be supported in an upcoming Windows release, but I am not aware of any plans to add support for opsets 11 at this time.

I've pushed updates to this page to specify 1909 support, and am closing this issue. Thank you for your patience.
