### ISSUE TITLE
Tensorflow example is incomplete

### ISSUE THREAD

**Issue by LarryThermo** [MicrosoftDocs/windows-ai-docs#18]
The tensorflow example is incomplete, where does the variable graph_pb2 come from? How do I create it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bf772d-9f06-0114-305a-058c6bea5786
* Version Independent ID: 297ca67d-9d10-eb87-f26e-4d72eefe252f
* Content: [Convert ML models to ONNX with WinMLTools](https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools#feedback)
* Content Source: [docs/windows-ml/convert-model-winmltools.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/convert-model-winmltools.md)
* Product: **machine-learning**
* GitHub Login: @wschin
* Microsoft Alias: **wechi**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
