### ISSUE TITLE
Word about free dimensions

### ISSUE THREAD

**Issue by BenPYeh** [MicrosoftDocs/windows-ai-docs#2]
Maybe add as a comment about free dimensions, particularly at where 'm_inputSkillDesc' is defined, that -1 is the designator for when we don't care about that dimension. 

But this brings up my concern where this doesn't seem to mesh with WinML. Say if you mean to edit your model with WinML Dashboard so that it has free dimensions, you don't put "-1" there you'd delete the entry and it gets a "None" placeholder. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd9c2f05-e537-3874-3ea2-bfc7b2f23558
* Version Independent ID: 9c57a643-914e-3c6b-4e55-2d069448bb77
* Content: [Create your own vision skill (C#/C++)](https://review.docs.microsoft.com/en-us/windows/ai-internal/windows-vision-skills/tutorial?branch=vision-skills-updates#feedback)
* Content Source: [docs/windows-vision-skills/tutorial.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/windows-vision-skills/tutorial.md)
* Product: **machine-learning**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
