### ISSUE TITLE
Failed to convert

### ISSUE THREAD

**Issue by tamero77** [MicrosoftDocs/windows-ai-docs#20]
Trying to convert my model from TF to Onnx, i keep getting the following error:
"Cannot infer shape for xxxxx"

should i somehow set the shape for the tensor? or is this a bug?

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
