### ISSUE TITLE
phi silica windows app sdk

### ISSUE THREAD

**Issue by manoj-jain-techporch** [MicrosoftDocs/windows-ai-docs#207]
Hi - I am trying to build a test app C# using this document. I have the Windows App SDK installed (1.6.240923002) and running VS2022 with latest SDKs. However, in the code when I attempt to include the name space, it can't find the namespace.

using Microsoft.Windows.AI.Generative; 

Is this depcrecated? Should we be using a specific NUGET pkg?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @manoj-jain-techporch,

The topic includes a note stating the following:

This feature is not yet available. It is expected to ship in an upcoming [experimental channel](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel) release of the Windows App SDK.
