### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by victor-mikhalev** [MicrosoftDocs/windows-ai-docs#21]
1. Install new W2019 server as hyper-v guest
2. Install Python in guest
3. run `pip install winmltools`

It wont install any way. Try you self. 

Could any one from support  or QA team try to do this steps on clean install?

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
