### ISSUE TITLE
The Windows Developer Feedback link is 404

### ISSUE THREAD

**Issue by Scottj1s** [MicrosoftDocs/windows-ai-docs#23]
"This UserVoice instance is no longer available."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc0a0e4-8dd3-07b2-78eb-2719d41c0c7d
* Version Independent ID: ecc8b6a5-bc5a-71e7-af0f-7aa9c9fcafe9
* Content: [Windows Vision Skills](https://docs.microsoft.com/en-us/windows/ai/windows-vision-skills/#feedback)
* Content Source: [docs/windows-vision-skills/index.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-vision-skills/index.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
