### ISSUE TITLE
Does this work with VisualBasic.Net?

### ISSUE THREAD

**Issue by popasUC** [MicrosoftDocs/windows-ai-docs#24]
Can Windows ML be used from Windows apps written in VB.Net and other .Net languages than C# (such as F#)?
If so, why list C# only and not state "any .Net language"? 
I am asking because this article is not an isolated flop, rather unfortunately seems to be part of a recently widespread practice at Microsoft, to omit VB.Net from documentation and other communications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e526d827-05b8-8e9a-80f5-c43562c1e182
* Version Independent ID: d8ea3163-5966-754a-0773-c4b40dd12654
* Content: [Introduction to Windows Machine Learning](https://docs.microsoft.com/en-us/windows/ai/windows-ml/#feedback)
* Content Source: [docs/windows-ml/index.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/index.md)
* Product: **machine-learning**
* GitHub Login: @rosanevallim
* Microsoft Alias: **rovalli**

**Comment by stevewhims** [comment]
Hi, @popasUC. Yes, we usually mention C# only in reference to .NET languages. We prioritize providing code examples in C#, and then C++/WinRT.

Thanks!
-Steve
