### ISSUE TITLE
The link to the tutorial is broken.

### ISSUE THREAD

**Issue by tfukumori** [MicrosoftDocs/windows-ai-docs#27]
I think the link to the tutorial is broken.

> There is also a **tutorial** that provides ...

https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions#onnx-opset-converter

Different:
https://github.com/onnx/tutorials/blob/master/tutorials/ExportModelFromPyTorchToDifferentONNXOpsetVersions.md

Correct:
https://github.com/onnx/tutorials/blob/master/tutorials/ExportModelFromPyTorchForWinML.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d4053d-f40c-68ac-b58e-7a73ce572714
* Version Independent ID: e584a5bd-c6fc-378f-26a5-968338147e85
* Content: [ONNX versions and Windows builds](https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions)
* Content Source: [docs/windows-ml/onnx-versions.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/onnx-versions.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by spillerrec** [comment]
This link is still broken. (I found this issue when searching for a working link)

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
