### ISSUE TITLE
error in example?

### ISSUE THREAD

**Issue by saund** [MicrosoftDocs/windows-ai-docs#3]
I think there may be an error in one of the examples.
In the section,
Convert Scikit-learn pipelines
you have:
pipeline = make_pipeline(normalizer, linear_svc)
...
pipeline_onnx = convert_sklearn(linear_svc, name='NormalizerLinearSVC',
                                input_features=[('input', FloatTensorType([1, 3]))])

Shouldn't this be:
pipeline_onnx = convert_sklearn(pipeline, name='NormalizerLinearSVC',
                                input_features=[('input', FloatTensorType([1, 3]))])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bf772d-9f06-0114-305a-058c6bea5786
* Version Independent ID: 297ca67d-9d10-eb87-f26e-4d72eefe252f
* Content: [Convert ML models to ONNX with WinMLTools](https://docs.microsoft.com/en-us/windows/ai/convert-model-winmltools#feedback)
* Content Source: [docs/convert-model-winmltools.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/convert-model-winmltools.md)
* Product: **machine-learning**
* GitHub Login: @wschin
* Microsoft Alias: **wechi**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
