### ISSUE TITLE
The onnx version control tutorial is broken

### ISSUE THREAD

**Issue by riaz** [MicrosoftDocs/windows-ai-docs#31]
[Enter feedback here]
The onnx version control tutorial is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d4053d-f40c-68ac-b58e-7a73ce572714
* Version Independent ID: e584a5bd-c6fc-378f-26a5-968338147e85
* Content: [ONNX versions and Windows builds](https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions)
* Content Source: [docs/windows-ml/onnx-versions.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/onnx-versions.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
