### ISSUE TITLE
No really, what is a model file

### ISSUE THREAD

**Issue by tpmeehan** [MicrosoftDocs/windows-ai-docs#33]
While the answer given for the question "What is a machine learning model" is technically correct, it stop short of a complete answer.  ie "A machine learning model is a file that has been trained to recognize certain types of patterns."  What is meant by a "file that has been trained"?  Files don't get trained, they are just bits and bytes on some storage media. I know this sound nit-picky but I am really looking for an answer to this question.  I presume what is meant is that the code that contains algorithms for detecting patterns somehow self-modifies to yield more accurate results - which is determined by how close it approximates the "correct" results.  But what does the model file itself contain?  Is it just an executable series of functions that take input and produce output to other functions in the chain? Or is there more to it.  Does the model file contain any of the training data after the training is done? OR Does the model file still contain a series of functions only with the weights and biases adjusted to yield the desired results?  Also are the contents of a model file human readable or are they compiled binary code.  I am very new to all of this but not new to software development.  As they say it's tough to teach an old dog new tricks. Bark bark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c85eacc-9626-25c6-fc68-c6c261827db7
* Version Independent ID: bfb7e704-bed6-7a36-cefe-813ba447ce67
* Content: [What is a machine learning model?](https://docs.microsoft.com/en-us/windows/ai/windows-ml/what-is-a-machine-learning-model)
* Content Source: [docs/windows-ml/what-is-a-machine-learning-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/what-is-a-machine-learning-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
