### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by AdamRLukaitis** [MicrosoftDocs/windows-ai-docs#34]
TOPIC: https://learn.microsoft.com/windows/ai/windows-ml/tutorials/advanced-tutorial-encryption

	// encrypt the model file.
	var encryptyed_buffer = await EncryptAsync(model_file);

	// decrypt the model file and load it
	await DecryptAndRunAsync(encryptyed_buffer);
	
should be
	
	// encrypt the model file.
	var encrypted_buffer = await EncryptAsync(model_file);

	// decrypt the model file and load it
	await DecryptAndRunAsync(encrypted_buffer);

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
