### ISSUE TITLE
Update with 21h2 announced gpu support in wsl2

### ISSUE THREAD

**Issue by ManuInNZ** [MicrosoftDocs/windows-ai-docs#36]
Hi 

Is there an update due following the announcement of gpu support in wsl 2 included in 21h2?

Cheers
Manu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdfa117-e801-0df5-3c81-3151a97f431d
* Version Independent ID: ee755d20-17c2-3d18-0c5c-b9ed31135218
* Content: [Enable NVIDIA CUDA in WSL 2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl)
* Content Source: [docs/directml/gpu-cuda-in-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-cuda-in-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @ManuInNZ, thanks for filing this issue. We'll update the topic in future once development/releases are a little further along.

Many thanks!
Steve
