### ISSUE TITLE
Code doesn't work with Visual Studio Community 2017

### ISSUE THREAD

**Issue by TomHammersley** [MicrosoftDocs/windows-ai-docs#4]
Hi there,

I tried this tutorial with Visual Studio Community 2017 and it doesn't compile out of the box. For example, the Windows namespaces needed prefixing with winrt::

I also needed to make sure the compiler was using /std:c++latest

Have I made an error, or is the content now inaccurate with the latest tools?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd39e3a-56da-5921-4e12-23278dcd49df
* Version Independent ID: 5de3959b-c507-bb89-4a0d-448e8ff3471f
* Content: [Windows Machine Learning for Desktop (C++) tutorial](https://docs.microsoft.com/en-us/windows/ai/get-started-desktop)
* Content Source: [docs/get-started-desktop.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/get-started-desktop.md)
* Product: **machine-learning**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by YanMiaoW** [comment]
Same issue, Code doesn't work with Visual Studio Community 2017, 
even if  prefixing with winrt::

**Comment by YanMiaoW** [comment]
Exception thrown at 0x00007FFCA8CC9129 (KernelBase.dll) in ConsoleApplication1.exe: WinRT originate error - 0x80070002 : 'Load model failed. File doesn't exist'.
'ConsoleApplication1.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFCA8CC9129 in ConsoleApplication1.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0000003FCDEFEEB8.

my path is : hstring modelPath = L"C:\\SqueezeNet.onnx";
It's existed.

**Comment by YanMiaoW** [comment]
I'm fixed. If you have the same problem, you should pay attention to the following points.
(1) before "using namespace Windows;" you must "using namespace winrt;"
(2) If you download a zip from "Windows-Machine-Learning Github repo", the unzip file name is "Windows-Machine-Learning-master", not ""Windows-Machine-Learning" In this tutorial.

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
