### ISSUE TITLE
`import torch` fails on ImportError: liblapack.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by qodfathr** [MicrosoftDocs/windows-ai-docs#44]
I was able to successfully follow the instructions on a fresh WSL2 / Ubuntu 20.04 installation.

Started interactive Python session and tried
`import python`

and got
```
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tmancini/miniconda3/envs/pydml/lib/python3.8/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
>>> ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
````
--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Version Independent ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Content: [Enable PyTorch with DirectML on WSL 2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl)
* Content Source: [docs/directml/gpu-pytorch-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @qodfathr, I'm investigating.

-Steve

**Comment by stevewhims** [comment]
It looks like this one has been addressed; the WSL docs were updated. But please reopen and/or respond if I'm mistaken.

-Steve
