### ISSUE TITLE
Mistakes in the code of Tutorial: Create a Windows Machine Learning Desktop application (C++)

### ISSUE THREAD

**Issue by HectorAnadon** [MicrosoftDocs/windows-ai-docs#48]
In step 7 of Load the model:
hstring should be removed as the variable is already defined in step 3 of Load the model.
In step 4 of Load the image:
hstring should be removed as the variable is already defined in step 3 of Load the model.
In step 5 of Evaluate the model:
Same here. string should be removed as the variable is already defined in step 3 of Load the model.

**Comment by eliotcowley** [comment]
Hi @HectorAnadon, these are actually places where we assign values to previously uninitialized variables, so we are not redefining them. I tried to make this a bit clearer by adding "where we defined it at the top" to each assignment. Thanks for being diligent, though!
