### ISSUE TITLE
EvaluateModel Method is not marked async

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/windows-ai-docs#5]
The logic contained in the EvaluateModel method contains an await keyword:

### Related Code
```csharp
await session.EvaluateAsync(...)
```

#### Option 1 (recommended): The method needs to be marked async and changed to a Task

```
private async Task EvaluateModel(
    LearningModelSession session, 
    LearningModelBinding binding,
    string outputName,
    List&lt;string&gt; labels)
{
   ...
    var results = await session.EvaluateAsync(binding, $"Run {++runCount}");
}
```

#### Option 2 (discouraged): Force the Task to return the result
```
var results = session.EvaluateAsync(binding, $"Run {++runCount}").Result;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9315e4b6-c17c-fc71-1b7a-8726c48fdb86
* Version Independent ID: 4f785ee5-e81b-2cdb-5af8-44e8e66158ee
* Content: [Evaluate the model inputs](https://docs.microsoft.com/en-us/windows/ai/evaluate-model-inputs)
* Content Source: [docs/evaluate-model-inputs.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/evaluate-model-inputs.md)
* Product: **machine-learning**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
