### ISSUE TITLE
NVIDIA driver download link broken

### ISSUE THREAD

**Issue by zakih** [MicrosoftDocs/windows-ai-docs#53]
Broken link: [Download and install NVIDIA's driver](https://developer.nvidia.com/cuda/wsl/download) 

also unclear which drivers, toolkits, etc. to install from NVIDIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505220ce-20d9-c5a6-08fc-89c83d1ba533
* Version Independent ID: f46d3107-c66a-0f0c-de6e-ae5de1eec242
* Content: [Tensorflow with DirectML on WSL](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-wsl)
* Content Source: [docs/directml/gpu-tensorflow-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-tensorflow-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Sorry for the delay in responding. I've updated the link.

-Steve
