### ISSUE TITLE
Nvidia CUDA driver broken link

### ISSUE THREAD

**Issue by bjarkebrodin** [MicrosoftDocs/windows-ai-docs#54]
Encountered broken link:

[NVIDIA CUDA enabled driver for WSL](https://developer.nvidia.com/cuda/wsl/download)

under section "Install the GPU driver"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdfa117-e801-0df5-3c81-3151a97f431d
* Version Independent ID: ee755d20-17c2-3d18-0c5c-b9ed31135218
* Content: [Enable NVIDIA CUDA on WSL 2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl)
* Content Source: [docs/directml/gpu-cuda-in-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-cuda-in-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @bjarkebrodin. I've published a fix now.
