### ISSUE TITLE
OS versions out of date

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/windows-ai-docs#58]
should Windows 11 and Windows Server 2022 be included in the OS list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e526d827-05b8-8e9a-80f5-c43562c1e182
* Version Independent ID: d8ea3163-5966-754a-0773-c4b40dd12654
* Content: [Introduction to Windows Machine Learning](https://docs.microsoft.com/en-us/windows/ai/windows-ml/)
* Content Source: [docs/windows-ml/index.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/index.md)
* Product: **machine-learning**
* GitHub Login: @rosanevallim
* Microsoft Alias: **rovalli**

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
