### ISSUE TITLE
Typo on paragraph 1

### ISSUE THREAD

**Issue by GCruz45** [MicrosoftDocs/windows-ai-docs#59]
Typo on paragraph 1: "scenario"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c9a4-f7d3-500c-33da-f4d0510ad809
* Version Independent ID: 24827753-8c8d-0741-2f88-f967b4595acc
* Content: [GPU acceleration in WSL](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-accelerated-training)
* Content Source: [docs/directml/gpu-accelerated-training.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-accelerated-training.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you, that's fixed now.
