### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by jfellien** [MicrosoftDocs/windows-ai-docs#60]
The most of the links are dead. So plase tell me how do you like to catch potential customers to your ai platform?

**Comment by stevewhims** [comment]
Hi, @jfellien. Which topic has the broken links? Thanks!

**Comment by QuinnRadich** [comment]
This repo has changed significantly since this issue was first raised, and further changes are upcoming. As such, I'm going through and closing many of these stale issues which sat unassigned for a long while.
