### ISSUE TITLE
Very Very please update your doc!

### ISSUE THREAD

**Issue by WqxLoveCoding** [MicrosoftDocs/windows-ai-docs#63]
[在此处输入反馈]
In the section ["Enable PyTorch with DirectML on WSL 2" - "Set up a Python environment"](https://docs.microsoft.com/zh-cn/windows/ai/directml/gpu-pytorch-wsl#set-up-a-python-environment), you recommend using Miniconda or Anaconda, while I find that now the built-in version of python3 on WSL 2 is Python 3.10.4, which is the latest version, but the last version that Miniconda or Anaconda supports is Python 3.9 (see [here](https://docs.conda.io/en/latest/miniconda.html#linux-installers) and [here](https://www.anaconda.com/products/distribution)), the thing is, if I directly follow your guides, I'm afraid some incompatibility problems would happen, which I cannot find any solutions from the Internet, or can U please provide some updates for this doc? I'm looking forward to your reply!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Version Independent ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Content: [Enable PyTorch with DirectML on WSL 2](https://docs.microsoft.com/zh-cn/windows/ai/directml/gpu-pytorch-wsl)
* Content Source: [docs/directml/gpu-pytorch-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you, I'm investigating.

-Steve

**Comment by zhangxiang1993** [comment]
Hi,

By today, pytorch-directml doesn't have support for python 3.9 and 3.10. We support python 3.6, 3.7 and 3.8, so Miniconda or Anaconda covers our scenario. By installing miniconda or anaconda, you could create virtual environment with specified python version, so that's why we recommend it.
