### ISSUE TITLE
Typo in tensor dimensions

### ISSUE THREAD

**Issue by kentmchenry** [MicrosoftDocs/windows-ai-docs#64]
[Enter feedback here]
The line `random 5x3 tensor` should read `random 2x3 tensor`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055f5223-92a5-b2d7-10d6-5bb6e85378ef
* Version Independent ID: ff28e52d-2870-a4e7-8931-52909412046d
* Content: [Install and configure PyTorch on your machine.](https://docs.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-installation)
* Content Source: [docs/windows-ml/tutorials/pytorch-installation.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-installation.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by stevewhims** [comment]
Fixed, thanks!
