### ISSUE TITLE
WINDOWS SDK BUILD link is not working 

### ISSUE THREAD

**Issue by eandreimv** [MicrosoftDocs/windows-ai-docs#65]
[Enter feedback here]
 This link from the page is not working anymore : [Windows SDK, build 17763 or later](https://www.microsoft.com/software-download/windowsinsiderpreviewSDK)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd39e3a-56da-5921-4e12-23278dcd49df
* Version Independent ID: 5de3959b-c507-bb89-4a0d-448e8ff3471f
* Content: [Windows Machine Learning for Desktop (C++) tutorial](https://docs.microsoft.com/en-us/windows/ai/windows-ml/get-started-desktop)
* Content Source: [docs/windows-ml/get-started-desktop.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/get-started-desktop.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

The link should be functioning now. This tutorial (among others here) is also likely to see significant changes in the near future.
