### ISSUE TITLE
Missing torchvision in WSL Debian

### ISSUE THREAD

**Issue by velicanerdem** [MicrosoftDocs/windows-ai-docs#76]
Hello,

I tried setting up on Debian version of WSL but there was no information about how to install torchvision, thus it was missing as a library. I think the guideline was missing information but it may not be expected behavior either. Using mobile (laptop) AMD CPU & GPU.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Version Independent ID: f802f4e7-0f89-fa4b-8977-2f9832990c3a
* Content: [Enable PyTorch with DirectML on WSL 2](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl)
* Content Source: [docs/directml/gpu-pytorch-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @velicanerdem, I'm investigating.

-Steve

**Comment by zhangxiang1993** [comment]
Hi,

For installing torchvision,[torchvision installation](https://github.com/pytorch/vision#installation)
1. git clone https://github.com/pytorch/vision.git
2. python setup.py install

Thanks for reporting this, we will update the guidance soon.
