### ISSUE TITLE
I need to degrade the protobuf from the version of 4.21.2 to the version of 3.20.1.

### ISSUE THREAD

**Issue by eternal-echo** [MicrosoftDocs/windows-ai-docs#77]
I try to set up my tensor environment step by step according to the tutorial, but it have some problems.
```
2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/home/yuanyu/miniconda3/envs/directml/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
Then I google this and degrade the protobuf from the version of 4.21.2 to the version of 3.20.1, then it works.
Maybe you can mark the version requirement of protobuf module.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 505220ce-20d9-c5a6-08fc-89c83d1ba533
* Version Independent ID: f46d3107-c66a-0f0c-de6e-ae5de1eec242
* Content: [TensorFlow with DirectML on WSL](https://docs.microsoft.com/zh-CN/windows/ai/directml/gpu-tensorflow-wsl#install-the-tensorflow-with-directml-package)
* Content Source: [docs/directml/gpu-tensorflow-wsl.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-tensorflow-wsl.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @eternal-echo! I'll investigate. :)

-Steve

**Comment by stevewhims** [comment]
Reopening while investigating.

**Comment by stevewhims** [comment]
Just an update: this issue is on the product team subject-matter experts' radar. They have all the info from this thread. So I'll go ahead and close this issue until such time as they have the bandwidth to address it.

-Steve
