### ISSUE TITLE
Error input type should be the same

### ISSUE THREAD

**Issue by dahler** [MicrosoftDocs/windows-ai-docs#80]
Got error on forward 
Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

happened here 

![image](https://user-images.githubusercontent.com/30863066/183292062-e9092c1a-bca4-47d7-a19c-ac330c0d0dd1.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54afee7-1e3b-98f3-c25d-c0d71b82bf97
* Version Independent ID: b75b9ae6-de0e-acc3-b9cd-4918422bf7aa
* Content: [Use PyTorch to train your image classification model](https://docs.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-train-model)
* Content Source: [docs/windows-ml/tutorials/pytorch-train-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-train-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by Z841973620** [comment]
Hey,

When I add additional judges in these two places, the program can run correctly.

Hope it can help you.

![image](https://user-images.githubusercontent.com/74134170/184493540-5fbdb174-35aa-4d0a-b3ce-e008ceb91082.png)

![image](https://user-images.githubusercontent.com/74134170/184493558-ecadc2d9-7c08-4fa3-89a4-efe4e822c65c.png)

**Comment by dahler** [comment]
Yes, I fixed this by adding almost the same piece of code 

![image](https://user-images.githubusercontent.com/30863066/184497091-e63a5795-7039-4bc3-9347-670482ad5fc7.png)
