### ISSUE TITLE
Ran this example from the top with cut and paste into miniconda and it just didn't work

### ISSUE THREAD

**Issue by crash1011** [MicrosoftDocs/windows-ai-docs#82]
[Enter feedback here]

As a newbie in MicroSoft world - tried this example from the top and it does not recognize DML - wants CPU/CUDA. My guess is that all versions (in requirements) need to be locked down to exact versions at the time of publishing for reproducibility.

Running Windows 10/Nvidia GPUS

Traceback (most recent call last):
  File "mike_pytorch_test.py", line 2, in <module>
    tensor1 = torch.tensor([1]).to("dml")
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 851931b0-0646-18fc-1c3b-5f5493524330
* Version Independent ID: 851931b0-0646-18fc-1c3b-5f5493524330
* Content: [Enable PyTorch with DirectML on Windows](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows)
* Content Source: [docs/directml/gpu-pytorch-windows.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/gpu-pytorch-windows.md)
* Product: **machine-learning**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @crash1011, I'm investigating.

-Steve

**Comment by crash1011** [comment]
Hi Steve,

Thanks for this - I am suspecting my later 11.7 cuda/nvidia hardware will cause more grief down the track but not sure what’s related to what yet … :(

**Comment by zhangxiang1993** [comment]
Hi,

please check your install python packages, you'll need to uninstall the previous installed torch package, and make sure pytorch-directml showing up in your pip list.
