### ISSUE TITLE
Dead Link on Page

### ISSUE THREAD

**Issue by kentmchenry** [MicrosoftDocs/windows-ai-docs#85]
A link refs a non-existant page in GitHub:

Here's a link to relevant section of the page:
https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/tensorflow-train-model#using-yolo

Here's the section with the dead link:
Using YOLO
First, download [this YOLO sample file](https://github.com/microsoft/DirectML/tree/master/TensorFlow/yolov3), which contains helper scripts to get started.

This is the dead end of the link (doesn't exist)
https://github.com/microsoft/DirectML/tree/master/TensorFlow/yolov3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2a37de-40da-e11c-e59e-803112ba2a65
* Version Independent ID: 20fdcb48-2333-be4f-3ce1-b910e92a02c2
* Content: [Train your ML model with TensorFlow](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/tensorflow-train-model)
* Content Source: [docs/windows-ml/tutorials/tensorflow-train-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/tensorflow-train-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I believe this problem has been resolved, and the update should be live shortly.
