### ISSUE TITLE
Dead video on Page 

### ISSUE THREAD

**Issue by primeMover2011** [MicrosoftDocs/windows-ai-docs#86]
[Enter feedback here]
The video at

[!VIDEO https://www.youtube.com/embed/8MCDSlm326U]

is unavailable because it is private...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70c5a5-6de6-8fa7-945e-d128cbb3f74e
* Version Independent ID: 9a5ee3f1-ea67-5b65-5a0f-c18f47f108df
* Content: [Automatic code generation with mlgen](https://learn.microsoft.com/en-us/windows/ai/windows-ml/mlgen)
* Content Source: [docs/windows-ml/mlgen.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/mlgen.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

This problem has been resolved, and the video has been removed.
