### ISSUE TITLE
loading coreml model (SentimentPolarity.mlmodel)

### ISSUE THREAD

**Issue by ssgwos** [MicrosoftDocs/windows-ai-docs#89]
c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\coremltools\models\utils.py:92: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  spec.ParseFromString(contents)

https://github.com/SwiftBrain/awesome-CoreML-models

**Comment by eliotcowley** [comment]
Hi @ssgwos, this repo is for WinML documentation. Do you have a specific issue on one of our docs? If not, I will close this issue.

**Comment by ssgwos** [comment]
wrong repo
