### ISSUE TITLE
Problem in converting tensorflow model to onnx

### ISSUE THREAD

**Issue by vinayak618** [MicrosoftDocs/windows-ai-docs#90]
When running the code to convert tf to onnx.
below is the error:
**graph_pb2 is not defined.**
is there any specific tf version to be used?, i'm using the latest 1.12.0.

**Comment by eliotcowley** [comment]
Hi @vinayak618, do you also have the latest version of [WinMLTools](https://pypi.org/project/winmltools/) installed? That would be version 1.3.0.

**Comment by youngkim93** [comment]
Hi @vinayak618, is the issue you are mentioning only happening on 16 bit quantization or 8 bit quantization only or did you get the same issue on the original model?

**Comment by vinayak618** [comment]
@youngbupark  @eliotcowley,
The issue i'm mentioning is happening only with 16bit and 8bit quantization and working fine for converted original model.

**Comment by youngkim93** [comment]
Hi @vinayak618, is it possible for you to share the converted tensorflow model with us? That will give us a good repro step to try out with WinML. By looking at the error message **unrecognized tensor datatype** It seems there is an issue with data type of the model. What data type (e.g float, int32, etc) are you using for your model?

**Comment by eliotcowley** [comment]
Hi @vinayak618, since we haven't heard from you in a while, I'm closing out this issue. Feel free to re-open it if you're still having trouble and you have more information to give us.
