### ISSUE TITLE
Invalid URL in `What is a machine learning model?`

### ISSUE THREAD

**Issue by Kelukin** [MicrosoftDocs/windows-ai-docs#90]
The URL [Emoji8 sample](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/Emoji8/UWP/cs)](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/Emoji8/UWP/cs) has been out-of-date and requires for updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e85c8e5b-d981-c2f3-2d27-927848fe7e66
* Version Independent ID: a10153c7-e612-f438-b35e-81004f1e9b6e
* Content: [What is a machine learning model?](https://learn.microsoft.com/en-us/windows/ai/windows-ml/what-is-a-machine-learning-model)
* Content Source: [docs/windows-ml/what-is-a-machine-learning-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/what-is-a-machine-learning-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I believe this problem has been resolved. This page is also likely to see further updates soon, along with many other docs in this space.
