### ISSUE TITLE
 ONNXInput() is not defined

### ISSUE THREAD

**Issue by FrOlsson** [MicrosoftDocs/windows-ai-docs#91]
Hi,

I also tried to follow this guide but runs into problems with  ONNXInput(). Where can I find it?

Kind regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0c6d66b-5fb4-5c4b-cfcc-6ea1e115ed27
* Version Independent ID: cf424133-78f5-6f65-aaac-4ee8a1840a24
* Content: [Deploy your PyTorch model in a Windows app with Windows ML API](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-deploy-model)
* Content Source: [docs/windows-ml/tutorials/pytorch-deploy-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-deploy-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I believe this problem has been resolved. Moreover, the tutorial in question is likely to see further updates soon, along with many other docs in this repo.
