### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bjbrianj** [MicrosoftDocs/windows-ai-docs#91]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c512e4e-eb91-cb1e-873e-7344689fe013
* Version Independent ID: f71d940c-2ca0-8248-3de7-ee6f1b15ea62
* Content: [Windows Machine Learning](https://docs.microsoft.com/en-us/windows/ai/)
* Content Source: [docs/index.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/master/docs/index.md)
* Product: **machine-learning**
* GitHub Login: @rosanevallim
* Microsoft Alias: **rovalli**

**Comment by bjbrianj** [comment]
So what is going on

**Comment by msamancioglu** [comment]
Can you create some sample applications written in C#/WinForms on GitHub.

**Comment by bjbrianj** [comment]
I don’t know how
