### ISSUE TITLE
did not get the second (automatic) ImageClassifier.cs file 

### ISSUE THREAD

**Issue by OwenRick** [MicrosoftDocs/windows-ai-docs#92]
I followed the instructions down to the T and never got the file in my solution explorer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b236fa85-23be-f5ec-5c5f-332937187f04
* Version Independent ID: 781552b8-a796-a963-05d3-ed98f509dbd4
* Content: [Convert your PyTorch training model to ONNX](https://learn.microsoft.com/en-us/windows/ai/windows-ml/tutorials/pytorch-convert-model)
* Content Source: [docs/windows-ml/tutorials/pytorch-convert-model.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/windows-ml/tutorials/pytorch-convert-model.md)
* Product: **machine-learning**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My apologies for letting this issue sit unassigned for such a long time.

I'm sorry to hear about your difficulties Without further information, there doesn't seem to be an actionable docs change from this issue (and this tutorial is slated for significant updates in the near future). I'm closing this issue for now.
